# Generated by Django 5.1.7 on 2025-03-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
